packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

catalogs:
  build:
    vite: ^6.3.6
    typescript: ^5.9.2
  format:
    '@ianvs/prettier-plugin-sort-imports': ^4.7.0
    prettier-plugin-packagejson: ^2.5.19
    prettier: ^3.6.2
  lint:
    '@eslint/js': ^9.36.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.36.0
    typescript-eslint: ^8.44.1
    jiti: ^2.6.0
  test:
    vitest: ^3.2.4
    '@vitest/browser': ^3.2.4
    '@playwright/test': ^1.55.1
  types:
    '@types/node': ^22.18.6
  script:
    'taze': '^19.7.0'
