packages:
  - packages/*
  - config/*

ignoredBuiltDependencies:
  - esbuild

catalogs:
  build:
    vite: ^6.4.0
    typescript: ^5.9.3
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier-plugin-packagejson: ^2.5.19
    prettier: ^3.6.2
  lint:
    "@eslint/js": ^9.38.0
    "@eslint/eslintrc": ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.38.0
    typescript-eslint: ^8.46.1
    jiti: ^2.6.1
  test:
    vitest: ^3.2.4
    "@vitest/browser": ^3.2.4
    "@playwright/test": ^1.56.1
  types:
    "@types/node": ^22.18.11
  script:
    "taze": "^19.8.0"
